# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *

class Ui_MainWindow(object):
    deleteyonghu=[]
    fixhuoche=[]
    deletehuoche=[]
    deletepiao=[]
    fixpiao = []
    deletelu=[]
    fixlu = []
    def setupUi(self, MainWindow,db,ui1,ui2,ui3,ch):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1090, 742)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 160, 141, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 210, 141, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 260, 141, 51))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 310, 141, 51))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 91, 71))
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(960, 660, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(160, 80, 791, 601))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 40, 72, 15))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1090, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton_2.clicked.connect(lambda: self.yonghu(db))
        self.pushButton_3.clicked.connect(lambda: self.huoche(db,ui1,ui2,ui3,ch))
        self.pushButton_4.clicked.connect(lambda: self.piao(db))
        self.pushButton_5.clicked.connect(lambda: self.luxian(db))
        self.label.setStyleSheet("color:red;")

        self.tableWidget.resizeRowsToContents()
        self.tableWidget.resizeColumnsToContents()
        # 只读不可修改
        self.tableWidget.setEditTriggers(QAbstractItemView.NoEditTriggers)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "用户管理"))
        self.pushButton_3.setText(_translate("MainWindow", "火车管理"))
        self.pushButton_4.setText(_translate("MainWindow", "票管理"))
        self.pushButton_5.setText(_translate("MainWindow", "路线管理"))
        self.pushButton.setText(_translate("MainWindow", "返回"))
        self.label_2.setText(_translate("MainWindow", "admin"))

    def yonghu(self, db):

        self.deleteyonghu.clear()
        self.tableWidget.clear()
        sql = "select * from 用户"
        cursor = db.cursor()
        cursor.execute(sql)
        results = cursor.fetchall()
        leng = len(results)
        for i in range(leng):
            B=QPushButton('删除')
            B.setStyleSheet('QPushButton{margin:3px};')
            self.deleteyonghu.append(B)
            self.deleteyonghu[i].clicked.connect(lambda: self.dy(db))


        self.tableWidget.setRowCount(leng)
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setHorizontalHeaderLabels(['姓名', '身份证号', '账号', '密码', '性别', '电话号','编辑'])

        for i in range(leng):
            ietm1 = QTableWidgetItem(results[i][0])
            ietm2 = QTableWidgetItem(results[i][1])
            ietm3 = QTableWidgetItem(results[i][2])
            ietm4 = QTableWidgetItem(results[i][3])
            ietm5 = QTableWidgetItem(results[i][4])
            ietm6 = QTableWidgetItem(results[i][5])

            self.tableWidget.setItem(i, 0, ietm1)
            self.tableWidget.setItem(i, 1, ietm2)
            self.tableWidget.setItem(i, 2, ietm3)
            self.tableWidget.setItem(i, 3, ietm4)
            self.tableWidget.setItem(i, 4, ietm5)
            self.tableWidget.setItem(i, 5, ietm6)
            self.tableWidget.setCellWidget(i, 6, self.deleteyonghu[i])







    def huoche(self, db,ui1,ui2,ui3,ch):
        self.deletehuoche.clear()
        self.tableWidget.clear()
        self.fixhuoche.clear()
        sql = "select * from 火车"
        cursor = db.cursor()
        cursor.execute(sql)
        results = cursor.fetchall()
        leng = len(results)
        print(leng)
        for i in range(leng):
            B=QPushButton('删除')
            B.setStyleSheet('QPushButton{margin:3px};')
            self.deletehuoche.append(B)
            self.deletehuoche[i].clicked.connect(lambda: self.dh(db))

        for i in range(leng):
            B = QPushButton('修改')
            B.setStyleSheet('QPushButton{margin:3px};')
            self.fixhuoche.append(B)
            self.fixhuoche[i].clicked.connect(lambda: self.fh(ui1,ui3,ch,db))
        B = QPushButton('增加')
        B.setStyleSheet('QPushButton{margin:3px};')

        self.deletehuoche.append(B)
        self.deletehuoche[leng].clicked.connect(lambda: self.ah(ui1,ui2))
        self.tableWidget.setRowCount(leng+1)
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setHorizontalHeaderLabels(['火车编号', '火车类型', '火车状态', '火车名字','编辑','修改'])
        for i in range(leng):
            ietm1 = QTableWidgetItem(results[i][0])
            ietm2 = QTableWidgetItem(results[i][1])
            ietm3 = QTableWidgetItem(results[i][2])
            ietm4 = QTableWidgetItem(results[i][3])
            self.hitem5 = QPushButton('删除')

            self.hitem5.setStyleSheet('QPushButton{margin:3px};')

            self.tableWidget.setItem(i, 0, ietm1)
            self.tableWidget.setItem(i, 1, ietm2)
            self.tableWidget.setItem(i, 2, ietm3)
            self.tableWidget.setItem(i, 3, ietm4)
            self.tableWidget.setCellWidget(i, 4, self.deletehuoche[i])
            self.tableWidget.setCellWidget(i, 5, self.fixhuoche[i])
        self.tableWidget.setCellWidget(leng, 4, self.deletehuoche[leng])

    def piao(self, db):
        self.fixpiao.clear()
        self.deletepiao.clear()
        self.tableWidget.clear()
        sql = "select * from 成人票"
        cursor = db.cursor()
        cursor.execute(sql)
        results = cursor.fetchall()
        leng = len(results)
        for i in range(leng):
            B=QPushButton('删除')
            B.setStyleSheet('QPushButton{margin:3px};')
            self.deletepiao.append(B)
            self.deletepiao[i].clicked.connect(lambda: self.dp(db))
        for i in range(leng):
            B = QPushButton('修改')
            B.setStyleSheet('QPushButton{margin:3px};')
            self.fixpiao.append(B)
        B = QPushButton('增加')
        B.setStyleSheet('QPushButton{margin:3px};')
        self.deletepiao.append(B)
        self.tableWidget.setRowCount(leng+1)
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setHorizontalHeaderLabels(['票编号', '路线编号', '火车编号', '价格', '座位', '类型', '车次','编辑'])
        for i in range(leng):
            ietm1 = QTableWidgetItem(results[i][0])
            ietm2 = QTableWidgetItem(results[i][1])
            ietm3 = QTableWidgetItem(results[i][4])

            ietm4 = QTableWidgetItem(str(results[i][5]))
            ietm5 = QTableWidgetItem(results[i][6])
            ietm6 = QTableWidgetItem(results[i][7])
            ietm7 = QTableWidgetItem(results[i][10])
            self.pitem8 = QPushButton('删除')

            self.pitem8.setStyleSheet('QPushButton{margin:3px};')

            self.tableWidget.setItem(i, 0, ietm1)
            self.tableWidget.setItem(i, 1, ietm2)
            self.tableWidget.setItem(i, 2, ietm3)
            self.tableWidget.setItem(i, 3, ietm4)
            self.tableWidget.setItem(i, 4, ietm5)
            self.tableWidget.setItem(i, 5, ietm6)
            self.tableWidget.setItem(i, 6, ietm7)
            self.tableWidget.setCellWidget(i, 7, self.deletepiao[i])

        self.tableWidget.setCellWidget(leng, 7, self.deletepiao[leng])


    def luxian(self, db):
        self.fixlu.clear()
        self.deletelu.clear()
        self.tableWidget.clear()
        sql = "select * from 路线"
        cursor = db.cursor()
        cursor.execute(sql)
        results = cursor.fetchall()
        leng = len(results)
        for i in range(leng):
            B = QPushButton('删除')
            B.setStyleSheet('QPushButton{margin:3px};')
            self.deletelu.append(B)
            self.deletelu[i].clicked.connect(lambda: self.dl(db))
        for i in range(leng):
            B = QPushButton('修改')
            B.setStyleSheet('QPushButton{margin:3px};')
            self.fixlu.append(B)
        B = QPushButton('增加')
        B.setStyleSheet('QPushButton{margin:3px};')
        self.deletelu.append(B)

        self.tableWidget.setRowCount(leng+1)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setHorizontalHeaderLabels(['路线编号', '起始点', '终点','编辑'])
        for i in range(leng):
            ietm1 = QTableWidgetItem(results[i][0])
            ietm2 = QTableWidgetItem(results[i][1])
            ietm3 = QTableWidgetItem(results[i][2])
            self.litem4 = QPushButton('删除')

            self.litem4 .setStyleSheet('QPushButton{margin:3px};')


            self.tableWidget.setItem(i, 0, ietm1)
            self.tableWidget.setItem(i, 1, ietm2)
            self.tableWidget.setItem(i, 2, ietm3)
            self.tableWidget.setCellWidget(i, 3, self.deletelu[i] )

        self.tableWidget.setCellWidget(leng,3,self.deletelu[leng])

    def dy(self,db):

        index=self.tableWidget.currentRow()
        str=self.tableWidget.item(index,2).text()
        sql="delete from 用户 where 账号='%s'"%(str)

        cursor=db.cursor()
        cursor.execute(sql)
        sql = "update 成人票 set valid='0 where 账号='%s'" % (str)
        cursor.execute(sql)
        msg_box = QMessageBox(QMessageBox.Information, '成功', '删除成功')
        msg_box.exec_()
        self.deleteyonghu.clear()
        self.tableWidget.clear()
        sql = "select * from 用户"
        cursor = db.cursor()
        cursor.execute(sql)
        results = cursor.fetchall()
        leng = len(results)
        for i in range(leng):
            B = QPushButton('删除')
            B.setStyleSheet('QPushButton{margin:3px};')
            self.deleteyonghu.append(B)
            self.deleteyonghu[i].clicked.connect(lambda: self.dy(db))

        self.tableWidget.setRowCount(leng)
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setHorizontalHeaderLabels(['姓名', '身份证号', '账号', '密码', '性别', '电话号', '编辑'])

        for i in range(leng):
            ietm1 = QTableWidgetItem(results[i][0])
            ietm2 = QTableWidgetItem(results[i][1])
            ietm3 = QTableWidgetItem(results[i][2])
            ietm4 = QTableWidgetItem(results[i][3])
            ietm5 = QTableWidgetItem(results[i][4])
            ietm6 = QTableWidgetItem(results[i][5])

            self.tableWidget.setItem(i, 0, ietm1)
            self.tableWidget.setItem(i, 1, ietm2)
            self.tableWidget.setItem(i, 2, ietm3)
            self.tableWidget.setItem(i, 3, ietm4)
            self.tableWidget.setItem(i, 4, ietm5)
            self.tableWidget.setItem(i, 5, ietm6)
            self.tableWidget.setCellWidget(i, 6, self.deleteyonghu[i])

    def dh(self,db):
        index = self.tableWidget.currentRow()
        str = self.tableWidget.item(index, 0).text()
        sql0="start transaction"
        sql1="set foreign_key_checks = 0"
        sql2 = "delete 火车,成人票 from 火车,成人票 where 火车.火车编号=成人票.火车编号 and 火车.火车编号='%s'" % (str)
        sql3 = "set foreign_key_checks = 1"
        sql4="commit"
        sql5="rollback"

        sql=[sql0,sql1,sql2,sql3,sql4,sql5]


        cursor = db.cursor()
        for i in sql:
            cursor.execute(i)

        msg_box = QMessageBox(QMessageBox.Information, '成功', '删除成功')
        msg_box.exec_()
        self.deletehuoche.clear()
        self.fixhuoche.clear()
        self.tableWidget.clear()
        sql = "select * from 火车"
        cursor = db.cursor()
        cursor.execute(sql)
        results = cursor.fetchall()
        leng = len(results)
        for i in range(leng):
            B = QPushButton('删除')
            B.setStyleSheet('QPushButton{margin:3px};')
            self.deletehuoche.append(B)
            self.deletehuoche[i].clicked.connect(lambda: self.dh(db))

        for i in range(leng):
            B = QPushButton('修改')
            B.setStyleSheet('QPushButton{margin:3px};')
            self.fixhuoche.append(B)
        B = QPushButton('增加')
        B.setStyleSheet('QPushButton{margin:3px};')

        self.deletehuoche.append(B)
        self.tableWidget.setRowCount(leng + 1)
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setHorizontalHeaderLabels(['火车编号', '火车类型', '火车状态', '火车名字', '编辑', '修改'])
        for i in range(leng):
            ietm1 = QTableWidgetItem(results[i][0])
            ietm2 = QTableWidgetItem(results[i][1])
            ietm3 = QTableWidgetItem(results[i][2])
            ietm4 = QTableWidgetItem(results[i][3])
            self.hitem5 = QPushButton('删除')

            self.hitem5.setStyleSheet('QPushButton{margin:3px};')

            self.tableWidget.setItem(i, 0, ietm1)
            self.tableWidget.setItem(i, 1, ietm2)
            self.tableWidget.setItem(i, 2, ietm3)
            self.tableWidget.setItem(i, 3, ietm4)
            self.tableWidget.setCellWidget(i, 4, self.deletehuoche[i])
            self.tableWidget.setCellWidget(i, 5, self.fixhuoche[i])
        self.tableWidget.setCellWidget(leng, 4, self.deletehuoche[leng])


    def dp(self,db):
        index = self.tableWidget.currentRow()
        str = self.tableWidget.item(index, 0).text()
        sql = "delete from 成人票 where 票编号='%s'" % (str)
        cursor = db.cursor()
        cursor.execute(sql)
        msg_box = QMessageBox(QMessageBox.Information, '成功', '删除成功')
        msg_box.exec_()
        self.fixpiao.clear()
        self.deletepiao.clear()
        self.tableWidget.clear()
        sql = "select * from 成人票"
        cursor = db.cursor()
        cursor.execute(sql)
        results = cursor.fetchall()
        leng = len(results)
        for i in range(leng):
            B = QPushButton('删除')
            B.setStyleSheet('QPushButton{margin:3px};')
            self.deletepiao.append(B)
            self.deletepiao[i].clicked.connect(lambda: self.dp(db))
        for i in range(leng):
            B = QPushButton('修改')
            B.setStyleSheet('QPushButton{margin:3px};')
            self.fixpiao.append(B)
        B = QPushButton('增加')
        B.setStyleSheet('QPushButton{margin:3px};')
        self.deletepiao.append(B)
        self.tableWidget.setRowCount(leng + 1)
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setHorizontalHeaderLabels(
            ['票编号', '路线编号', '火车编号', '价格', '座位', '类型', '车次', '编辑', '修改'])
        for i in range(leng):
            ietm1 = QTableWidgetItem(results[i][0])
            ietm2 = QTableWidgetItem(results[i][1])
            ietm3 = QTableWidgetItem(results[i][4])
            ietm4 = QTableWidgetItem(str(results[i][5]))
            ietm5 = QTableWidgetItem(results[i][6])
            ietm6 = QTableWidgetItem(results[i][7])
            ietm7 = QTableWidgetItem(results[i][10])
            self.pitem8 = QPushButton('删除')

            self.pitem8.setStyleSheet('QPushButton{margin:3px};')

            self.tableWidget.setItem(i, 0, ietm1)
            self.tableWidget.setItem(i, 1, ietm2)
            self.tableWidget.setItem(i, 2, ietm3)
            self.tableWidget.setItem(i, 3, ietm4)
            self.tableWidget.setItem(i, 4, ietm5)
            self.tableWidget.setItem(i, 5, ietm6)
            self.tableWidget.setItem(i, 6, ietm7)
            self.tableWidget.setCellWidget(i, 7, self.deletepiao[i])
            self.tableWidget.setCellWidget(i, 8, self.fixpiao[i])
        self.tableWidget.setCellWidget(leng, 7, self.deletepiao[leng])


    def dl(self,db):
        index = self.tableWidget.currentRow()
        str = self.tableWidget.item(index, 0).text()

        sql0 = "start transaction"
        sql1 = "set foreign_key_checks =0"
        sql2 = "delete 路线,成人票 from 路线,成人票 where 路线.路线编号=成人票.路线编号 and 路线.路线编号='%s'" % (str)

        sql3 = "set foreign_key_checks = 1"
        sql4 = "commit"
        sql5 = "rollback"

        sql = [sql0, sql1, sql2, sql3, sql4, sql5]
        cursor = db.cursor()
        for i in sql:
            cursor.execute(i)


        msg_box = QMessageBox(QMessageBox.Information, '成功', '删除成功')
        msg_box.exec_()
        self.deletelu.clear()
        self.tableWidget.clear()
        sql = "select * from 路线"
        cursor = db.cursor()
        cursor.execute(sql)
        results = cursor.fetchall()
        leng = len(results)
        for i in range(leng):
            B = QPushButton('删除')
            B.setStyleSheet('QPushButton{margin:3px};')
            self.deletelu.append(B)
            self.deletelu[i].clicked.connect(lambda: self.dl(db))

        self.tableWidget.setRowCount(leng)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setHorizontalHeaderLabels(['路线编号', '起始点', '终点', '编辑'])
        for i in range(leng):
            ietm1 = QTableWidgetItem(results[i][0])
            ietm2 = QTableWidgetItem(results[i][1])
            ietm3 = QTableWidgetItem(results[i][2])
            self.litem4 = QPushButton('删除')

            self.litem4.setStyleSheet('QPushButton{margin:3px};')

            self.tableWidget.setItem(i, 0, ietm1)
            self.tableWidget.setItem(i, 1, ietm2)
            self.tableWidget.setItem(i, 2, ietm3)
            self.tableWidget.setCellWidget(i, 3, self.deletelu[i])

    def ah(self,ui1,ui2):
        ui1.close()
        ui2.show()

    def fh(self,ui1,ui2,ch,db):
        index = self.tableWidget.currentRow()
        str = self.tableWidget.item(index, 0).text()
        str1 = self.tableWidget.item(index, 1).text()
        str2= self.tableWidget.item(index, 2).text()
        str3 = self.tableWidget.item(index, 3).text()
        ui1.close()
        ch.setupUi(ui2,str,str1,str2,str3,db)
        ch.pushButton_2.clicked.connect(lambda :self.ah(ui2,ui1))
        ui2.show()







