# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fixinfor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow,db,me):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 597)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 50, 151, 41))
        self.label.setText("")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(260, 140, 181, 41))
        self.lineEdit.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(260, 210, 181, 41))
        self.lineEdit_2.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(260, 280, 181, 41))
        self.lineEdit_3.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(260, 350, 181, 41))
        self.lineEdit_4.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(260, 410, 181, 41))
        self.lineEdit_5.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(560, 410, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(560, 460, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.pushButton.clicked.connect(lambda :self.yes(me,db))
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "姓名"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "性别"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "电话号"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "账号"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "密码"))
        self.pushButton.setText(_translate("MainWindow", "确定"))
        self.pushButton_2.setText(_translate("MainWindow", "返回"))
    def yes(self,me,db):
        id=me.id
        name=self.lineEdit.text()
        sex= self.lineEdit_2.text()
        phone = self.lineEdit_3.text()
        zhanghao = self.lineEdit_4.text()
        password = self.lineEdit_5.text()

        id='%s'%id
        name = '%s' % self.lineEdit.text()
        sex = '%s' % self.lineEdit_2.text()
        phone = '%s' % self.lineEdit_3.text()
        zhanghao = '%s' % self.lineEdit_4.text()
        password = '%s' % self.lineEdit_5.text()
        sql0="select * from 用户 where 账号='%s'"%(zhanghao)
        cursor = db.cursor()
        cursor.execute(sql0)
        print(sql0)
        result=cursor.fetchone()
        print(result)
        if result!=None:
            msg_box = QMessageBox(QMessageBox.Critical, '错误', '该用户已存在')
            msg_box.exec_()
        else:
            sql0="set foreign_key_checks = 0"
            cursor.execute(sql0)

            sql = "CALL fixinfor('%s','%s','%s','%s','%s','%s')" % (name, id, zhanghao, sex, phone, password)
            try:
                cursor.execute(sql)
                db.commit()
                me.initial(name, id, zhanghao, password, sex, phone)
                msg_box = QMessageBox(QMessageBox.Information, '成功', '修改成功')
                msg_box.exec_()

            except:
                msg_box = QMessageBox(QMessageBox.Information, '失败', '修改失败')
                msg_box.exec_()
            sql0 = "set foreign_key_checks = 1"
            cursor.execute(sql0)







